### PR TITLE
The checker was failing to apply DoNotUse/NoExternalUse to nested members

### PR DESCRIPTION
**Pull request by jglick**
After #3 it seems the checker was still not doing its job. https://github.com/jenkinsci/support-core-plugin/pull/137 should not have been necessary, yet actually other plugins were able to call

```java
Helper.getActiveInstance()
```

without errors.

@reviewbybees esp. @dwnusbaum

### CODE REVIEW

**Comment by jglick** [comment]
Ignore the broken Travis build BTW.

**Comment by amuniz** [comment]
I bet there is some API client relying on the existence of this bug (probably unintentional) and this fix is going to break it. Perhaps printing a big fat log message for some time before applying the final fix will avoid pain...

**Comment by jglick** [comment]
> I bet there is some API client relying on the existence of this bug (probably unintentional) and this fix is going to break it.

Yes, that is the idea! If you have no other option, you can always hold back on the Maven plugin update.

**Comment by jglick** [comment]
…but I am working on a patch to allow `skip` and `failOnError` parameters in line with what other similar mojos define.

**Pull request merged**
