### PR TITLE
ASM5 fix

### PR DESCRIPTION
**Pull request by jglick**
Corrects a critical regression in #2.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Yes…not trivial to write I think. [This idiom](https://github.com/infradna/bridge-method-injector/blob/7dfabe76b73207b3184444034a69ea726907e4eb/injector/pom.xml#L36-L126) is one possibility but probably `maven-invoker-plugin` and `src/its` is the right approach. Let me think about whether I can do this without a lot of hassle.

**Comment by jtnord** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by jglick** [comment]
@kohsuke can you merge and release this, or grant me write access to the repository and deploy permission to this artifact on https://oss.sonatype.org/?

**Comment by jglick** [comment]
FTR this is how I deployed a snapshot of this PR to the Jenkins repository, bypassing OSSRH, for purposes of making it available for integration testing in downstream PRs:

    mvn clean install deploy:deploy -DaltDeploymentRepository=maven.jenkins-ci.org::default::https://repo.jenkins-ci.org/snapshots/ -DskipNexusStagingDeployMojo

thanks to [this tip](http://stackoverflow.com/a/30799934/12916).

**Pull request merged**
